apiVersion: v1

kind: ConfigMap

metadata:

  name: aws-auth

  namespace: kube-system

data:

  mapRoles: |

    - rolearn: arn:aws:iam::902649160275:role/EKSBootcampRole

      username: build

      groups:

        - system:masters

