apiVersion: v1

kind: ConfigMap

metadata:
  name: aws-auth

  namespace: kube-system

data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::371198079589:role/FullEKSPermission
      username: system:node:{{EC2PrivateDNSName}}
